import Header from '@/components/header'
import styles from './layout.module.css'
import SearchInput from '@/components/searchInput'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.root}>
        <NuqsAdapter>
          <Header />
          <SearchInput placeholder="Search by Brand, Product or Category" />
          <main>{children}</main>
          <footer>This is the footer</footer>
        </NuqsAdapter>
      </body>
    </html>
  )
}
