import Header from '@/components/header'
import styles from './layout.module.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={styles.root}>
        <Header />
        <main>{children}</main>
        <footer>This is the footer</footer>
      </body>
    </html>
  )
}
