import Header from '@/components/header'
import styles from './layout.module.css'
import SearchInput from '@/components/SearchInput'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import Footer from '@/components/Footer'
import Head from 'next/head'
import SearchMenu from '@/components/SearchMenu'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.root}>
        <NuqsAdapter>
          <Header />
          <SearchInput placeholder="Search by Brand, Product or Category" />
          <SearchMenu />
          <main className={styles.main}>{children}</main>
          <Footer />
        </NuqsAdapter>
      </body>
    </html>
  )
}
